project:
  name: Fusarium
  organism: Fusarium
  taxon: Fungi
input:
  fasta: /mnt/d/interpro/test_fasta.fasta
interproscan:
  enabled: true
  reuse_existing: false
  existing_result: ''
  datadir: /mnt/d/interpro/Functional_Analysis/raw/InterProScan
  repository: https://github.com/ebi-pf-team/interproscan6
  profile: docker
  goterms: true
  pathways: true
  formats: tsv
  max_workers: 4
blast:
  enabled: true
  database: ''
  database_name: UniProtKB/Swiss-Prot
  evalue: 1.0e-05
  max_target_seqs: 5
  max_hsps: 1
resources:
  go_obo: /mnt/d/interpro/GO/go-basic.obo
  goslim_obo: /mnt/d/interpro/GO/goslim_generic.obo
  interpro2go: /mnt/d/interpro/GO/interpro2go.txt
  interproscan_datadir: /mnt/d/interpro/Functional_Analysis/raw/InterProScan
  blast_database: ''
settings:
  cpus: 4
  resume: true
  create_excel: true
  copy_input_fasta: true
output:
  directory: /home/govardhan/FusariumAnnotator_RELEASE/14_ARI_Wheat_Pathology_Functional_Annotation/results/Fusarium
  excel_file: Fusarium_Protein_Annotation.xlsx
  blast_file: BLAST_SwissProt.tsv
